name: Bug Report
description: Bug report for testing team
title: "[BUG] "
labels: ["bug", "qa"]
body:
  - type: input
    id: bug-id
    attributes:
      label: Bug ID
      description: Internal tracking ID (if applicable)
      placeholder: "BUG-1234"
    validations:
      required: false
  - type: textarea
    id: summary
    attributes:
      label: Bug Summary
      description: Brief, clear description of the defect
      placeholder: "Login button not responding on mobile devices"
    validations:
      required: true
  
  - type: textarea
    id: preconditions
    attributes:
      label: Preconditions
      description: Setup/state required before reproducing
      placeholder: |
        - User must be logged out
        - Clear cache and cookies
    validations:
      required: false
  
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Blocker (stops testing/release)
        - Critical (major functionality broken)
        - Major (significant impact)
        - Minor (low impact)
        - Trivial (cosmetic)
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - P0 (fix immediately)
        - P1 (fix before release)
        - P2 (fix soon)
        - P3 (fix when possible)
    validations:
      required: true
      
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Navigate to login page
        2. Enter valid credentials
        3. Click "Login" button
        4. Observe no response
    validations:
      required: true
  
  - type: textarea
    id: actual
    attributes:
      label: Actual Result
      description: What actually happens (the bug)
      placeholder: "Login button does not respond, user remains on login page"
    validations:
      required: true
  
  - type: textarea
    id: expected
    attributes:
      label: Expected Result
      description: What should happen
      placeholder: "User should be logged in and redirected to dashboard"
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Error Messages/Logs
      description: Console errors, stack traces, log files
      render: shell
    validations:
      required: false
  
  - type: textarea
    id: attachments
    attributes:
      label: Screenshots/Videos
      description: Visual evidence of the bug
    validations:
      required: false
